#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const packageJsonPath = path.join(root, 'package.json')
const versionPath = path.join(root, 'src', 'version.ts')

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'))
const version = packageJson.version

if (!version || typeof version !== 'string') {
  throw new Error('package.json must define a string version')
}

const content = `// Auto-generated by scripts/generate-version.js. Do not edit manually.
// Source: package.json

export const VERSION = '${version}'
export const CLIENT_VERSION = VERSION
export const MIN_SERVER_API_VERSION = 'v1'

export const VERSION_INFO = {
  version: VERSION,
  name: 'automation-action'
} as const
`

fs.writeFileSync(versionPath, content)
