import { readFileSync, writeFileSync } from 'node:fs'

const pkg = JSON.parse(
  readFileSync(new URL('../package.json', import.meta.url))
)
const outputPath = new URL('../src/version.ts', import.meta.url)

const content = `// Auto-generated by scripts/generate-version.js. Do not edit manually.
// Source: package.json

export const VERSION = '${pkg.version}'
export const CLIENT_VERSION = VERSION
export const MIN_SERVER_API_VERSION = 'v1'

export const VERSION_INFO = {
  version: VERSION,
  name: 'automation-action'
} as const
`

writeFileSync(outputPath, content)
