// Auto-generated by scripts/generate-version.js. Do not edit manually.
// Source: package.json

export const VERSION = '1.0.8'
export const CLIENT_VERSION = VERSION
export const MIN_SERVER_API_VERSION = 'v1'

export const VERSION_INFO = {
  version: VERSION,
  name: 'automation-action'
} as const
